name: Deploy to Anypoint Exchange
description: Deploy to Anypoint Exchange with Maven
inputs:
  connected_app_client_id:
    description: Connected app client ID
    required: true
  connected_app_client_secret:
    description: Connected app client secret
    required: true
  business_group_id:
    description: Business group ID
    required: true
  maven_settings_path:
    description: Maven settings file path
    required: true
  mule_file_path:
    description: Mule file path
    required: true
  mule_runtime_version:
    description: Mule runtime version
    default: 4.4.0

runs:
  using: composite
  steps:
    - name: Deploy to Anypoint Exchange
      shell: bash
      run: |
        mvn deploy --settings ${{ inputs.maven_settings_path }} -DskipTests
      env:
        CONNECTED_APP_CLIENT_ID: ${{ inputs.connected_app_client_id }}
        CONNECTED_APP_CLIENT_SECRET: ${{ inputs.connected_app_client_secret }}
        MULE_RUNTIME_VERSION: ${{ inputs.mule_runtime_version }}
        BUSINESS_GROUP_ID: ${{ inputs.business_group_id }}
