name: Deploy to CloudHub
description: Deploy to CloudHub with Maven
inputs:
  artifact_name:
    description: Artifact name
    default: build-artifacts
  download_artifact:
    description: Download artifact
    default: 'false'
  connected_app_client_id:
    description: CloudHub connected app client ID
    required: true
  connected_app_client_secret:
    description: CloudHub connected app client secret
    required: true
  cloudhub_environment:
    description: CloudHub environment
    required: true
  cloudhub_application_name:
    description: CloudHub application name
    required: true
  mule_version:
    description: Mule version
    default: 4.4.0

runs:
  using: composite
  steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      if: inputs.download_artifact == 'true'
      with:
        name: ${{ inputs.artifact_name }}
        path: target

    - name: Deploy to CloudHub
      shell: bash
      run: |
        artifactName=$(ls target/*.jar | head -1)
        mvn deploy -DskipTests -DmuleDeploy -Dartifact=${artifactName} -X -e
      env:
        CONNECTED_APP_CLIENT_ID: ${{ inputs.connected_app_client_id }}
        CONNECTED_APP_CLIENT_SECRET: ${{ inputs.connected_app_client_secret }}
        CLOUDHUB_ENVIRONMENT: ${{ inputs.cloudhub_environment }}
        CLOUDHUB_APPLICATION_NAME: ${{ inputs.cloudhub_application_name }}
        MULE_VERSION: ${{ inputs.mule_version }}
