name: Deploy to Exchange 1.0
description: Deploy to Exchange 1.0 with Maven
inputs:
  nexus_username:
    description: Nexus enterprise repository username
    required: true
  nexus_password:
    description: Nexus enterprise repository password
    required: true
  maven_settings_path:
    description: Maven settings file path
    required: true
  mule_file_path:
    description: Mule file path
    required: true
  cloudhub_business_group_id:
    description: CloudHub business group ID
  mule_runtime_version:
    description: Mule runtime version
    default: 4.4.0

runs:
  using: composite
  steps:
    - name: Deploy to Exchange
      shell: bash
      run: |
        mvn deploy --settings ${{ inputs.maven_settings_path }} -DskipTests -DbusinessGroupId=${CLOUDHUB_BUSINESS_GROUP_ID}
      env:
        NEXUS_USERNAME: ${{ inputs.nexus_username }}
        NEXUS_PASSWORD: ${{ inputs.nexus_password }}
        MULE_RUNTIME_VERSION: ${{ inputs.mule_runtime_version }}
        CLOUDHUB_BUSINESS_GROUP_ID: ${{ inputs.cloudhub_business_group_id }}
