name: Deploy to Exchange 1.0
description: Deploy to Exchange 1.0 with Maven
inputs:
  use_artifact:
    description: Download artifact
    default: 'true'
  artifact_name:
    description: Artifact name
    default: build-artifacts
  mule_file_path:
    description: Mule file path
    required: true
  connected_app_client_id:
    description: CloudHub connected app client ID
    required: true
  connected_app_client_secret:
    description: CloudHub connected app client secret
    required: true
  mule_runtime_version:
    description: Mule runtime version
    default: 4.4.0

runs:
  using: composite
  steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      if: inputs.use_artifact == 'true'
      with:
        name: ${{ inputs.artifact_name }}

    - name: Deploy to Exchange
      shell: bash
      run: |
        artifactName=${{ inputs.mule_file_path }}
        mvn deploy -DskipTests -Dartifact=${artifactName}
      env:
        CONNECTED_APP_CLIENT_ID: ${{ inputs.connected_app_client_id }}
        CONNECTED_APP_CLIENT_SECRET: ${{ inputs.connected_app_client_secret }}
        MULE_RUNTIME_VERSION: ${{ inputs.mule_runtime_version }}
