name: Deploy to Exchange 1.0
description: Deploy to Exchange 1.0 with Maven
inputs:
  connected_app_client_id:
    description: CloudHub connected app client ID
    required: true
  connected_app_client_secret:
    description: CloudHub connected app client secret
    required: true
  maven_settings_path:
    description: Maven settings file path
    required: true
  mule_file_path:
    description: Mule file path
    required: true
  cloudhub_business_group_id:
    description: CloudHub business group ID
  mule_runtime_version:
    description: Mule runtime version
    default: 4.4.0

runs:
  using: composite
  steps:
    - name: Deploy to Exchange
      shell: bash
      run: |
        mvn deploy --settings ${{ inputs.maven_settings_path }} -DskipTests -DbusinessGroupId=${CLOUDHUB_BUSINESS_GROUP_ID}
      env:
        CONNECTED_APP_CLIENT_ID: ${{ inputs.connected_app_client_id }}
        CONNECTED_APP_CLIENT_SECRET: ${{ inputs.connected_app_client_secret }}
        MULE_RUNTIME_VERSION: ${{ inputs.mule_runtime_version }}
        CLOUDHUB_BUSINESS_GROUP_ID: ${{ inputs.cloudhub_business_group_id }}
