name: Bump version for doc
description: Bump version for doc
inputs:
  new_version:
    description: New version
    required: true
  version_file:
    description: Version file
    default: exchange.json
  committer:
    description: Committer for the pull request
    required: true
  assignees:
    description: Assignees for the pull request
    required: true
  github_token:
    description: GitHub token to create the pull request
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set the new version in ${{ inputs.version_file }}
      shell: bash
      run: |
        sed -i "s/\"version\": \".*\"/\"version\": \"${{ inputs.new_version }}\"/" ${{ inputs.version_file }}
        cat ${{ inputs.version_file }}

    - name: Create the pull request
      uses: peter-evans/create-pull-request@v5
      with:
        assignees: ${{ inputs.assignees }}
        token: ${{ inputs.github_token }}
        commit-message: Bump version to ${{ inputs.new_version }}
        committer: ${{ inputs.committer }}
        branch: chore/bump-version-to-${{ inputs.new_version }}
        delete-branch: true
        title: "[Chore] Bump version to ${{ inputs.new_version }}"
        labels: |
          type : chore
        body: |
          ## What happened 👀

          Bump version to ${{ inputs.new_version }}

          ## Insight 📝

          Automatically created by the Bump Version workflow.

          ## Proof Of Work 📹

          On the Files changed tab
