name: Set up Mulesoft environment
description: Set up JDK environment and cache
inputs:
  java_version:
    description: Java version to use
    required: true
    default: 8
  java_distribution:
    description: Java distribution to use
    required: true
    default: zulu

runs:
  using: composite
  steps:
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven

    - uses: actions/setup-java@v3
      with:
        distribution: ${{ inputs.java_distribution }}
        java-version: ${{ inputs.java_version }}
