name: Deploy to Anypoint Exchange

on:
  workflow_call:
    inputs:
      maven_settings_path:
        description: Maven settings file path
        type: string
        required: true
        default: .maven/settings.xml
      mule_runtime_version:
        type: string
        required: true
        default: 4.4.0
    secrets:
      CONTD_APP_CLIENT_ID:
        required: true
      CONTD_APP_CLIENT_SECRET:
        required: true
      BUSINESS_GROUP_ID:
        required: true

jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Mulesoft environment
        uses: nimblehq/mulesoft-actions/setup@v1.5

      - name: Build with Maven
        uses: nimblehq/mulesoft-actions/build@v1.5
        id: build
        with:
          use_artifacts: false
          connected_app_client_id: ${{ secrets.CONTD_APP_CLIENT_ID }}
          connected_app_client_secret: ${{ secrets.CONTD_APP_CLIENT_SECRET }}
          business_group_id: ${{ secrets.BUSINESS_GROUP_ID }}
          nexus_username: ${{ secrets.NEXUS_USERNAME }}
          nexus_password: ${{ secrets.NEXUS_PASSWORD }}
          maven_settings_path: ${{ inputs.maven_settings_path }}

      - name: Deploy to Anypoint Exchange
        uses: nimblehq/mulesoft-actions/deploy_exchange@v1.5
        with:
          connected_app_client_id: ${{ secrets.CONTD_APP_CLIENT_ID }}
          connected_app_client_secret: ${{ secrets.CONTD_APP_CLIENT_SECRET }}
          maven_settings_path: ${{ inputs.maven_settings_path }}
          business_group_id: ${{ secrets.BUSINESS_GROUP_ID }}
          mule_file_path: ${{ steps.build.outputs.mule_file_path }}
          mule_runtime_version: ${{ inputs.mule_runtime_version }}
