name: Deploy to CloudHub 1.0

on:
  workflow_call:
    inputs:
      cloudhub_region:
        type: string
        required: true
      cloudhub_environment:
        type: string
        required: true
      cloudhub_application_name:
        type: string
      mule_runtime_version:
        type: string
        required: true
        default: 4.4.0
      maven_settings_path:
        description: Maven settings file path
        type: string
        required: true
        default: .maven/settings.xml
      number_of_workers:
        description: Number of workers
        type: string
        required: false
        default: '1'
      http_log_level:
        description: HTTP Log Level (OFF, FATAL, ERROR, WARN, INFO, DEBUG, TRACE, ALL)
        type: string
        required: false
        default: 'OFF'
      main_api_interface_path:
        description: Main APIKit interface path
        type: string
        required: false
      timeout_minutes:
        description: The maximum number of minutes to let a job run before GitHub automatically cancels it.
        type: number
        required: false
        default: 15
    secrets:
      CONTD_APP_CLIENT_ID:
        required: true
      CONTD_APP_CLIENT_SECRET:
        required: true
      PLATFORM_CLIENT_ID:
        required: false
      PLATFORM_CLIENT_SECRET:
        required: false
      BUSINESS_GROUP_ID:
        required: true
      ENCRYPTION_KEY:
        required: true
      NEXUS_USERNAME:
        required: false
      NEXUS_PASSWORD:
        required: false
      NEW_RELIC_API_KEY:
        required: false

jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.timeout_minutes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Remove when switching to the new Exchange - BUSINESS_GROUP_ID_GLOBAL_2 completely for all ENV (DEV, STAGING, PROD)
      - name: Modify groupId in pom.xml
        shell: bash
        run: |
          perl -0777 -pe 's/<groupId>[0-9a-fA-F\-]+<\/groupId>/<groupId>${{ secrets.BUSINESS_GROUP_ID }}<\/groupId>/g' -i.bak pom.xml
          cat pom.xml

      # Remove when switching to the new Exchange - BUSINESS_GROUP_ID_GLOBAL_2 completely for all ENV (DEV, STAGING, PROD)
      - name: Modify groupId in Main API Interface
        if: ${{ inputs.main_api_interface_path }}
        shell: bash
        run: |
          perl -0777 -pe 's/resource::[0-9a-fA-F\-]+/resource::${{ secrets.BUSINESS_GROUP_ID }}/' -i.bak ${{ inputs.main_api_interface_path }}
          cat ${{ inputs.main_api_interface_path }}

      - name: Set up Mulesoft environment
        uses: nimblehq/mulesoft-actions/setup@v1.11.0

      - name: Build with Maven
        uses: nimblehq/mulesoft-actions/build@v1.11.0
        id: build
        with:
          use_artifacts: false
          connected_app_client_id: ${{ secrets.CONTD_APP_CLIENT_ID }}
          connected_app_client_secret: ${{ secrets.CONTD_APP_CLIENT_SECRET }}
          business_group_id: ${{ secrets.BUSINESS_GROUP_ID }}
          nexus_username: ${{ secrets.NEXUS_USERNAME }}
          nexus_password: ${{ secrets.NEXUS_PASSWORD }}
          maven_settings_path: ${{ inputs.maven_settings_path }}

      - name: Deploy to CloudHub
        uses: nimblehq/mulesoft-actions/deploy_cloudhub_1_0@v1.11.0
        with:
          connected_app_client_id: ${{ secrets.CONTD_APP_CLIENT_ID }}
          connected_app_client_secret: ${{ secrets.CONTD_APP_CLIENT_SECRET }}
          platform_client_id: ${{ secrets.PLATFORM_CLIENT_ID }}
          platform_client_secret: ${{ secrets.PLATFORM_CLIENT_SECRET }}
          cloudhub_environment: ${{ inputs.cloudhub_environment }}
          cloudhub_region: ${{ inputs.cloudhub_region }}
          business_group_id: ${{ secrets.BUSINESS_GROUP_ID }}
          cloudhub_application_name: ${{ inputs.cloudhub_application_name }}
          use_artifact: false
          mule_file_path: ${{ steps.build.outputs.mule_file_path }}
          mule_runtime_version: ${{ inputs.mule_runtime_version }}
          encryption_key: ${{ secrets.ENCRYPTION_KEY }}
          nexus_username: ${{ secrets.NEXUS_USERNAME }}
          nexus_password: ${{ secrets.NEXUS_PASSWORD }}
          new_relic_api_key: ${{ secrets.NEW_RELIC_API_KEY }}
          maven_settings_path: ${{ inputs.maven_settings_path }}
          number_of_workers: ${{ inputs.number_of_workers }}
          http_log_level: ${{ inputs.http_log_level }}
