name: Deploy to CloudHub 1.0

on:
  workflow_call:
    inputs:
      mule_runtime_version:
        type: string
        default: 4.4.0
    secrets:
      CONTD_APP_CLIENT_ID:
        required: true
      CONTD_APP_CLIENT_SECRET:
        required: true
      BUSINESS_GROUP_ID:
        required: true

jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Mulesoft environment
        uses: nimblehq/mulesoft-actions/setup@v1

      - name: Build with Maven
        uses: nimblehq/mulesoft-actions/build@v1
        id: build
        with:
          use_artifacts: false

      - name: Deploy to Exchange
        uses: nimblehq/mulesoft-actions/deploy_exchange_1_0@v1.0
        with:
          connected_app_client_id: ${{ secrets.CONTD_APP_CLIENT_ID }}
          connected_app_client_secret: ${{ secrets.CONTD_APP_CLIENT_SECRET }}
          use_artifact: false
          mule_file_path: ${{ steps.build.outputs.mule_file_path }}
          mule_runtime_version: ${{ inputs.mule_runtime_version }}
