name: Deploy to Anypoint Exchange

on:
  workflow_call:
    inputs:
      maven_settings_path:
        description: Maven settings file path
        type: string
        required: true
        default: .maven/settings.xml
      mule_runtime_version:
        type: string
        required: true
        default: 4.4.0
      timeout-minutes:
        description: The maximum number of minutes to let a job run before GitHub automatically cancels it.
        type: string
        required: false
        default: 15
    secrets:
      CONTD_APP_CLIENT_ID:
        required: true
      CONTD_APP_CLIENT_SECRET:
        required: true
      BUSINESS_GROUP_ID:
        required: true

jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.timeout-minutes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Remove when switching to the new Exchange - BUSINESS_GROUP_ID_GLOBAL_2 completely for all ENV (DEV, STAGING, PROD)
      - name: Modify groupId in pom.xml
        shell: bash
        run: |
          perl -0777 -pe 's/<groupId>[0-9a-fA-F\-]+<\/groupId>/<groupId>${{ secrets.BUSINESS_GROUP_ID }}<\/groupId>/' -i.bak pom.xml
          cat pom.xml

      - name: Set up Mulesoft environment
        uses: nimblehq/mulesoft-actions/setup@v1.5

      - name: Build with Maven
        uses: nimblehq/mulesoft-actions/build@v1.5
        id: build
        with:
          use_artifacts: false

      - name: Deploy to Anypoint Exchange
        uses: nimblehq/mulesoft-actions/deploy_exchange@v1.5
        with:
          connected_app_client_id: ${{ secrets.CONTD_APP_CLIENT_ID }}
          connected_app_client_secret: ${{ secrets.CONTD_APP_CLIENT_SECRET }}
          maven_settings_path: ${{ inputs.maven_settings_path }}
          business_group_id: ${{ secrets.BUSINESS_GROUP_ID }}
          mule_file_path: ${{ steps.build.outputs.mule_file_path }}
          mule_runtime_version: ${{ inputs.mule_runtime_version }}
