name: Test

on:
  workflow_call:
    inputs:
      maven_settings_path:
        description: Maven settings file path
        type: string
        default: .maven/settings.xml
      upload_coverage_reports:
        description: Upload MUnit reports to GitHub Actions Artifacts
        type: boolean
        default: false
    secrets:
      NEXUS_USERNAME:
        required: true
      NEXUS_PASSWORD:
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run shared tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Mulesoft environment
        uses: nimblehq/mulesoft-actions/setup@v1

      - name: Run MUnit tests
        uses: nimblehq/mulesoft-actions/test@v1
        with:
          nexus_username: ${{ secrets.NEXUS_USERNAME }}
          nexus_password: ${{ secrets.NEXUS_PASSWORD }}
          maven_settings_path: ${{ inputs.maven_settings_path }}
          upload_coverage_reports: ${{ inputs.upload_coverage_reports }}
