name: Test

on:
  workflow_call:
    inputs:
      maven_settings_path:
        description: Maven settings file path
        type: string
        required: true
        default: .maven/settings.xml
      upload_coverage_reports:
        description: Upload MUnit reports to GitHub Actions Artifacts
        type: boolean
        default: true
      timeout_minutes:
        description: The maximum number of minutes to let a job run before GitHub automatically cancels it.
        type: string
        required: false
        default: 15
    secrets:
      NEXUS_USERNAME:
        required: true
      NEXUS_PASSWORD:
        required: true
      ENCRYPTION_KEY:
        required: true
      CONTD_APP_CLIENT_ID:
        required: false
      CONTD_APP_CLIENT_SECRET:
        required: false
      BUSINESS_GROUP_ID:
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run shared tests
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.timeout_minutes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Mulesoft environment
        uses: nimblehq/mulesoft-actions/setup@v1.5

      - name: Run MUnit tests
        uses: nimblehq/mulesoft-actions/test@v1.5
        with:
          nexus_username: ${{ secrets.NEXUS_USERNAME }}
          nexus_password: ${{ secrets.NEXUS_PASSWORD }}
          maven_settings_path: ${{ inputs.maven_settings_path }}
          upload_coverage_reports: ${{ inputs.upload_coverage_reports }}
          encryption_key: ${{ secrets.ENCRYPTION_KEY }}
          connected_app_client_id: ${{ secrets.CONTD_APP_CLIENT_ID }}
          connected_app_client_secret: ${{ secrets.CONTD_APP_CLIENT_SECRET }}
          business_group_id: ${{ secrets.BUSINESS_GROUP_ID }}
