name: Deploy to CloudHub 1.0

on:
  workflow_call:
    inputs:
      cloudhub_region:
        type: string
        required: true
      cloudhub_environment:
        type: string
        required: true
      cloudhub_application_name:
        type: string
      mule_runtime_version:
        type: string
        default: 4.4.0
    secrets:
      CONTD_APP_CLIENT_ID:
        required: true
      CONTD_APP_CLIENT_SECRET:
        required: true
      CLOUDHUB_BUSINESS_GROUP_ID:
        required: true

jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Mulesoft environment
        uses: nimblehq/mulesoft-actions/setup@v1

      - name: Build with Maven
        uses: nimblehq/mulesoft-actions/build@v1
        id: build
        with:
          use_artifacts: false

      - name: Deploy to CloudHub
        uses: nimblehq/mulesoft-actions/deploy_cloudhub_1_0@v1
        with:
          connected_app_client_id: ${{ secrets.CONTD_APP_CLIENT_ID }}
          connected_app_client_secret: ${{ secrets.CONTD_APP_CLIENT_SECRET }}
          cloudhub_environment: ${{ inputs.cloudhub_environment }}
          cloudhub_region: ${{ inputs.cloudhub_region }}
          cloudhub_business_group_id: ${{ secrets.CLOUDHUB_BUSINESS_GROUP_ID }}
          cloudhub_application_name: ${{ inputs.cloudhub_application_name }}
          use_artifact: false
          mule_file_path: ${{ steps.build.outputs.mule_file_path }}
          mule_runtime_version: ${{ inputs.mule_runtime_version }}
